# Generated by Django 5.1.1 on 2024-09-06 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monreqs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringrequest",
            name="logins",
            field=models.ManyToManyField(
                related_name="monreqs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="monitoringrequest",
            name="status",
            field=models.CharField(
                choices=[("O", "Em andamento"), ("P", "Pendente"), ("C", "Cancelada")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="monitoringrequest",
            name="vehicle",
            field=models.CharField(
                choices=[
                    ("BXT", "Caminhão baú"),
                    ("LCV", "VUC"),
                    ("TCR", "Caminhão reboque"),
                ],
                max_length=3,
            ),
        ),
    ]
