/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusEnum } from './StatusEnum';
import {
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
} from './StatusEnum';
import type { VehicleTypeEnum } from './VehicleTypeEnum';
import {
    VehicleTypeEnumFromJSON,
    VehicleTypeEnumFromJSONTyped,
    VehicleTypeEnumToJSON,
} from './VehicleTypeEnum';

/**
 * 
 * @export
 * @interface PatchedMonReq
 */
export interface PatchedMonReq {
    /**
     * 
     * @type {number}
     * @memberof PatchedMonReq
     */
    readonly pk?: number;
    /**
     * 
     * @type {StatusEnum}
     * @memberof PatchedMonReq
     */
    status?: StatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedMonReq
     */
    readonly statusDisplay?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedMonReq
     */
    shippingCompany?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedMonReq
     */
    origin?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedMonReq
     */
    destination?: string;
    /**
     * 
     * @type {VehicleTypeEnum}
     * @memberof PatchedMonReq
     */
    vehicleType?: VehicleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedMonReq
     */
    cargoDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedMonReq
     */
    cargoValue?: number;
}



/**
 * Check if a given object implements the PatchedMonReq interface.
 */
export function instanceOfPatchedMonReq(value: object): value is PatchedMonReq {
    return true;
}

export function PatchedMonReqFromJSON(json: any): PatchedMonReq {
    return PatchedMonReqFromJSONTyped(json, false);
}

export function PatchedMonReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedMonReq {
    if (json == null) {
        return json;
    }
    return {
        
        'pk': json['pk'] == null ? undefined : json['pk'],
        'status': json['status'] == null ? undefined : StatusEnumFromJSON(json['status']),
        'statusDisplay': json['status_display'] == null ? undefined : json['status_display'],
        'shippingCompany': json['shipping_company'] == null ? undefined : json['shipping_company'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'vehicleType': json['vehicle_type'] == null ? undefined : VehicleTypeEnumFromJSON(json['vehicle_type']),
        'cargoDescription': json['cargo_description'] == null ? undefined : json['cargo_description'],
        'cargoValue': json['cargo_value'] == null ? undefined : json['cargo_value'],
    };
}

export function PatchedMonReqToJSON(value?: Omit<PatchedMonReq, 'pk'|'status_display'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': StatusEnumToJSON(value['status']),
        'shipping_company': value['shippingCompany'],
        'origin': value['origin'],
        'destination': value['destination'],
        'vehicle_type': VehicleTypeEnumToJSON(value['vehicleType']),
        'cargo_description': value['cargoDescription'],
        'cargo_value': value['cargoValue'],
    };
}

