/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `BXT` - BXT
 * * `LCV` - LCV
 * * `TCR` - TCR
 * @export
 */
export const VehicleTypeEnum = {
    Bxt: 'BXT',
    Lcv: 'LCV',
    Tcr: 'TCR'
} as const;
export type VehicleTypeEnum = typeof VehicleTypeEnum[keyof typeof VehicleTypeEnum];


export function instanceOfVehicleTypeEnum(value: any): boolean {
    for (const key in VehicleTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(VehicleTypeEnum, key)) {
            if (VehicleTypeEnum[key as keyof typeof VehicleTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VehicleTypeEnumFromJSON(json: any): VehicleTypeEnum {
    return VehicleTypeEnumFromJSONTyped(json, false);
}

export function VehicleTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleTypeEnum {
    return json as VehicleTypeEnum;
}

export function VehicleTypeEnumToJSON(value?: VehicleTypeEnum | null): any {
    return value as any;
}

